### ISSUE TITLE
Groupe chat/error msg when next

### ISSUE THREAD

**Issue by Shwallows** [lodev09/sbotify#2]
The commands doesnt work in groupe chat.
Do everyone need to add the bot in their contact list?

**Comment by Shwallows** [comment]
i got it working as long you put @ infront of the name. The commands works but it gets me error message.

![bilde](https://user-images.githubusercontent.com/39730049/40654184-d5f9c7b0-633d-11e8-87b2-c79abe95eea8.png)

**Comment by lodev09** [comment]
run init first `@sbotify init`
